### ISSUE TITLE
[Question] What is missing requires to release version 1.1.0?

### ISSUE THREAD

**Issue by Jarod42** [kallisti5/guisan#121]
I wonder if we can tag (and release?) version "soon".

Current version is mostly compatible with Guichan 0.9.0 (all their commits has been back-ported).

I plan to *"break"* API with future changes (smart pointer, adding const to some virtual methods, ...)
and targeting another version would be fine for that.

**Comment by midwan** [comment]
Sounds good to me :)

**Comment by Jarod42** [comment]
@kallisti5
Which is the release process?
Tagging and create Release from Github is enough, or do we have to do more?
Do you prefer to do it yourself, or can we do it?

**Comment by Jarod42** [comment]
[v1.1.0 released](https://github.com/kallisti5/guisan/releases/tag/v1.1.0)
