### ISSUE TITLE
Button widgets don't trigger mouseEntered properly

### ISSUE THREAD

**Issue by midwan** [kallisti5/guisan#17]
I noticed this on the Raspberry Pi platforms, but not on others. Even with the provided sample/demo applications.

The issue is:
- Clicking on a Button widget with the left mouse button, selects the button but does not trigger/push it.
- Clicking on a Button and moving the mouse by at least 1 pixel, works as expected (the button is pushed).

From all the widgets I tested, only buttons seem to have this issue.

I managed to track this down to the `src/widgets/button.cpp` file, and specifically to this:

The `mouseReleased()` event is not triggered if we have a left mouse button event, because `mHasMouse` is false.

`mHasMouse` is changed by the `mouseEntered()` and `mouseExited()` events. These events are triggered correctly only when the mouse is "dragged" over a button, but not when it's clicked.

As a simple work around, I removed the requirement for `mHasMouse` to be `true` for the `mouseReleased()` event, and I also changed `isPressed()` slightly to return the status of `mMousePressed` instead of `mHasMouse`, for updating the draw event properly.

I didn't notice any issues with this approach. Is there something else we could do, that might be a better solution?

**Comment by Jarod42** [comment]
Checking `hasMouse` in `mouseReleased` is for case when we push the button, then move the mouse outside of button before releasing the button.
I don't see the benefit of `mHasMouse` instead of a direct check though.
a workaround if we keep `mHasMouse` is to set it on `mousePressed`.
