### ISSUE TITLE
Management of darker and lighter color

### ISSUE THREAD

**Issue by gbaudic** [kallisti5/guisan#20]
In several widgets (at least Scrollarea and Button with its derived classes), some computation on the colors are done to get darker or lighter colors, for example to make a button look pressed down. Unfortunately, the code to do this always follows a pattern similar to: 

``highlightColor = faceColor + 0x303030;``

I am afraid that while it works perfectly on grey shades, it is going to be unsuitable if the widgets are made to be colored in almost every other color.  
A possible solution I see would be, instead of adding or subtracting a fixed amount on red, green and blue channels, to use a multiplicative coefficient on these three channels so the hue is kept but only the luminosity varies.

**Comment by midwan** [comment]
This should be fixed now, after the widget fixes #75 
I'm using custom colors in the GUI of my own project, and with this fix you also get widgets that are not Enabled to properly show as greyed out (even the text).
